import { Astrologer } from "@/constants/types";

export const Astrologers: Astrologer[] = [
  {
    id: "1",
    name: "Guru Shankar",
    image: require("@/assets/images/astrologers/astrologer2.png"),
    rating: 4.5,
    speciality: "Prashana",
    experience: 10,
    price: 2.99,
    language: ["English", "Hindi"],
    orders: 120,
    availability: "Available",
    category: ["Career & Job", "Finance & Business"],
  },
  {
    id: "2",
    name: "Astro Priya",
    image: require("@/assets/images/astrologers/astrologer1.png"),
    rating: 4.8,
    speciality: "Physicologist",
    experience: 5,
    price: 3.99,
    language: ["English", "Spanish"],
    orders: 80,
    availability: "Available",
    category: ["Love & Relationship", "Education"],
  },
  {
    id: "3",
    name: "Astro Neha",
    image: require("@/assets/images/astrologers/astrologer3.png"),
    rating: 4.7,
    speciality: "Numerology",
    experience: 7,
    price: 4.99,
    language: ["Hindi", "Urdu"],
    orders: 95,
    availability: "Available",
    category: ["Kids", "Education"],
  },
  {
    id: "4",
    name: "Astro Vikram",
    image: require("@/assets/images/astrologers/astrologer1.png"),
    rating: 4.6,
    speciality: "Palmistry",
    experience: 8,
    price: 3.49,
    language: ["English", "Hindi"],
    orders: 110,
    availability: "Available",
    category: ["Finance & Business", "Martial Status"],
  },
  {
    id: "5",
    name: "Astro Riya",
    image: require("@/assets/images/astrologers/astrologer2.png"),
    rating: 4.9,
    speciality: "Vedic",
    experience: 6,
    price: 5.99,
    language: ["English", "French"],
    orders: 70,
    availability: "Available",
    category: ["Love & Relationship", "Martial Status"],
  },
  {
    id: "6",
    name: "Astro Kiran",
    image: require("@/assets/images/astrologers/astrologer3.png"),
    rating: 4.4,
    speciality: "Tarot",
    experience: 4,
    price: 2.49,
    language: ["English", "Hindi"],
    orders: 60,
    availability: "Available",
    category: ["Kids", "Finance & Business"],
  },
  {
    id: "7",
    name: "Astro Meera",
    image: require("@/assets/images/astrologers/astrologer2.png"),
    rating: 4.3,
    speciality: "Vastu",
    experience: 9,
    price: 3.79,
    language: ["English", "Tamil"],
    orders: 85,
    availability: "Available",
    category: ["Career & Job", "Education"],
  },
  {
    id: "8",
    name: "Astro Raj",
    image: require("@/assets/images/astrologers/astrologer1.png"),
    rating: 4.2,
    speciality: "Horary",
    experience: 11,
    price: 4.29,
    language: ["Hindi", "English"],
    orders: 130,
    availability: "Available",
    category: ["Finance & Business", "Martial Status"],
  },
  {
    id: "9",
    name: "Astro Sneha",
    image: require("@/assets/images/astrologers/astrologer3.png"),
    rating: 4.1,
    speciality: "Western",
    experience: 3,
    price: 2.99,
    language: ["English", "Bengali"],
    orders: 55,
    availability: "Available",
    category: ["Love & Relationship", "Kids"],
  },
  {
    id: "10",
    name: "Astro Aman",
    image: require("@/assets/images/astrologers/astrologer2.png"),
    rating: 4.0,
    speciality: "Chinese",
    experience: 8,
    price: 3.59,
    language: ["English", "Hindi"],
    orders: 100,
    availability: "Available",
    category: ["Career & Job", "Education"],
  },
  {
    id: "11",
    name: "Astro Kavya",
    image: require("@/assets/images/astrologers/astrologer1.png"),
    rating: 4.7,
    speciality: "Numerology",
    experience: 6,
    price: 4.19,
    language: ["English", "Kannada"],
    orders: 90,
    availability: "Available",
    category: ["Finance & Business", "Martial Status"],
  },
  {
    id: "12",
    name: "Astro Dev",
    image: require("@/assets/images/astrologers/astrologer2.png"),
    rating: 4.5,
    speciality: "Palmistry",
    experience: 7,
    price: 3.99,
    language: ["English", "Hindi"],
    orders: 105,
    availability: "Available",
    category: ["Love & Relationship", "Kids"],
  },
  {
    id: "13",
    name: "Astro Ritu",
    image: require("@/assets/images/astrologers/astrologer3.png"),
    rating: 4.6,
    speciality: "Vedic",
    experience: 5,
    price: 5.49,
    language: ["English", "Punjabi"],
    orders: 75,
    availability: "Available",
    category: ["Career & Job", "Finance & Business"],
  },
  {
    id: "14",
    name: "Astro Suresh",
    image: require("@/assets/images/astrologers/astrologer1.png"),
    rating: 4.8,
    speciality: "Prashana",
    experience: 12,
    price: 2.99,
    language: ["English", "Hindi"],
    orders: 140,
    availability: "Available",
    category: ["Love & Relationship", "Martial Status"],
  },
  {
    id: "15",
    name: "Astro Pooja",
    image: require("@/assets/images/astrologers/astrologer2.png"),
    rating: 4.9,
    speciality: "Tarot",
    experience: 9,
    price: 6.29,
    language: ["English", "Gujarati"],
    orders: 65,
    availability: "Available",
    category: ["Kids", "Finance & Business"],
  },
];

export const OngoingAstrologers = [
  {
    id: "1",
    name: "Guru Shankar",
    image: require("@/assets/images/astrologers/astrologer2.png"),
    date: "2023-10-15",
    time: "10:00 AM",
  },
  {
    id: "2",
    name: "Astro Priya",
    image: require("@/assets/images/astrologers/astrologer1.png"),
    date: "2023-10-16",
    time: "11:30 AM",
  },
  {
    id: "3",
    name: "Astro Neha",
    image: require("@/assets/images/astrologers/astrologer3.png"),
    date: "2023-10-17",
    time: "02:00 PM",
  },
  {
    id: "4",
    name: "Astro Vikram",
    image: require("@/assets/images/astrologers/astrologer1.png"),
    date: "2023-10-18",
    time: "03:30 PM",
  },
  {
    id: "5",
    name: "Astro Riya",
    image: require("@/assets/images/astrologers/astrologer2.png"),
    date: "2023-10-19",
    time: "05:00 PM",
  },
  {
    id: "6",
    name: "Astro Kiran",
    image: require("@/assets/images/astrologers/astrologer3.png"),
    date: "2023-10-20",
    time: "06:30 PM",
  },
];

export const UpcomingAstrologers = [
  {
    id: "1",
    name: "Guru Shankar",
    image: require("@/assets/images/astrologers/astrologer2.png"),
    date: "2023-10-15",
    time: "10:00 AM",
  },
  {
    id: "2",
    name: "Astro Priya",
    image: require("@/assets/images/astrologers/astrologer1.png"),
    date: "2023-10-16",
    time: "11:30 AM",
  },
  {
    id: "3",
    name: "Astro Neha",
    image: require("@/assets/images/astrologers/astrologer3.png"),
    date: "2023-10-17",
    time: "02:00 PM",
  },
  {
    id: "4",
    name: "Astro Vikram",
    image: require("@/assets/images/astrologers/astrologer1.png"),
    date: "2023-10-18",
    time: "03:30 PM",
  },
  {
    id: "5",
    name: "Astro Riya",
    image: require("@/assets/images/astrologers/astrologer2.png"),
    date: "2023-10-19",
    time: "05:00 PM",
  },
  {
    id: "6",
    name: "Astro Kiran",
    image: require("@/assets/images/astrologers/astrologer3.png"),
    date: "2023-10-20",
    time: "06:30 PM",
  },
  {
    id: "7",
    name: "Astro Kiran",
    image: require("@/assets/images/astrologers/astrologer3.png"),
    date: "2023-10-20",
    time: "06:30 PM",
  },
];
