import { Astrologer } from "@/constants/types";

export const adsdfsd: Astrologer[] = [
  {
    id: "1",
    name: "Guru Shankar",
    image: require("@/assets/images/astrologers/astrologer2.png"),
    rating: 4.5,
    speciality: "Prashana",
    experience: 10,
    price: 2.99,
    language: ["English", "Hindi"],
    orders: 120,
    availability: "Available",
    category: ["Career & Job", "Finance & Business"],
  },
  {
    id: "2",
    name: "Astro Priya",
    image: require("@/assets/images/astrologers/astrologer1.png"),
    rating: 4.8,
    speciality: "Physicologist",
    experience: 5,
    price: 3.99,
    language: ["English", "Spanish"],
    orders: 80,
    availability: "Available",
    category: ["Love & Relationship", "Education"],
  },
  {
    id: "3",
    name: "Astro Neha",
    image: require("@/assets/images/astrologers/astrologer3.png"),
    rating: 4.7,
    speciality: "Numerology",
    experience: 7,
    price: 4.99,
    language: ["Hindi", "Urdu"],
    orders: 95,
    availability: "Available",
    category: ["Kids", "Education"],
  },
  {
    id: "4",
    name: "Astro Vikram",
    image: require("@/assets/images/astrologers/astrologer1.png"),
    rating: 4.6,
    speciality: "Palmistry",
    experience: 8,
    price: 3.49,
    language: ["English", "Hindi"],
    orders: 110,
    availability: "Available",
    category: ["Finance & Business", "Martial Status"],
  },
  {
    id: "5",
    name: "Astro Riya",
    image: require("@/assets/images/astrologers/astrologer2.png"),
    rating: 4.9,
    speciality: "Vedic",
    experience: 6,
    price: 5.99,
    language: ["English", "French"],
    orders: 70,
    availability: "Available",
    category: ["Love & Relationship", "Martial Status"],
  },
  {
    id: "6",
    name: "Astro Kiran",
    image: require("@/assets/images/astrologers/astrologer3.png"),
    rating: 4.4,
    speciality: "Tarot",
    experience: 4,
    price: 2.49,
    language: ["English", "Hindi"],
    orders: 60,
    availability: "Available",
    category: ["Kids", "Finance & Business"],
  },
  {
    id: "7",
    name: "Astro Meera",
    image: require("@/assets/images/astrologers/astrologer2.png"),
    rating: 4.3,
    speciality: "Vastu",
    experience: 9,
    price: 3.79,
    language: ["English", "Tamil"],
    orders: 85,
    availability: "Available",
    category: ["Career & Job", "Education"],
  },
  {
    id: "8",
    name: "Astro Raj",
    image: require("@/assets/images/astrologers/astrologer1.png"),
    rating: 4.2,
    speciality: "Horary",
    experience: 11,
    price: 4.29,
    language: ["Hindi", "English"],
    orders: 130,
    availability: "Available",
    category: ["Finance & Business", "Martial Status"],
  },
  {
    id: "9",
    name: "Astro Sneha",
    image: require("@/assets/images/astrologers/astrologer3.png"),
    rating: 4.1,
    speciality: "Western",
    experience: 3,
    price: 2.99,
    language: ["English", "Bengali"],
    orders: 55,
    availability: "Available",
    category: ["Love & Relationship", "Kids"],
  },
  {
    id: "10",
    name: "Astro Aman",
    image: require("@/assets/images/astrologers/astrologer2.png"),
    rating: 4.0,
    speciality: "Chinese",
    experience: 8,
    price: 3.59,
    language: ["English", "Hindi"],
    orders: 100,
    availability: "Available",
    category: ["Career & Job", "Education"],
  },
  {
    id: "11",
    name: "Astro Kavya",
    image: require("@/assets/images/astrologers/astrologer1.png"),
    rating: 4.7,
    speciality: "Numerology",
    experience: 6,
    price: 4.19,
    language: ["English", "Kannada"],
    orders: 90,
    availability: "Available",
    category: ["Finance & Business", "Martial Status"],
  },
  {
    id: "12",
    name: "Astro Dev",
    image: require("@/assets/images/astrologers/astrologer2.png"),
    rating: 4.5,
    speciality: "Palmistry",
    experience: 7,
    price: 3.99,
    language: ["English", "Hindi"],
    orders: 105,
    availability: "Available",
    category: ["Love & Relationship", "Kids"],
  },
  {
    id: "13",
    name: "Astro Ritu",
    image: require("@/assets/images/astrologers/astrologer3.png"),
    rating: 4.6,
    speciality: "Vedic",
    experience: 5,
    price: 5.49,
    language: ["English", "Punjabi"],
    orders: 75,
    availability: "Available",
    category: ["Career & Job", "Finance & Business"],
  },
  {
    id: "14",
    name: "Astro Suresh",
    image: require("@/assets/images/astrologers/astrologer1.png"),
    rating: 4.8,
    speciality: "Prashana",
    experience: 12,
    price: 2.99,
    language: ["English", "Hindi"],
    orders: 140,
    availability: "Available",
    category: ["Love & Relationship", "Martial Status"],
  },
  {
    id: "15",
    name: "Astro Pooja",
    image: require("@/assets/images/astrologers/astrologer2.png"),
    rating: 4.9,
    speciality: "Tarot",
    experience: 9,
    price: 6.29,
    language: ["English", "Gujarati"],
    orders: 65,
    availability: "Available",
    category: ["Kids", "Finance & Business"],
  },
  // {
  //   id: "16",
  //   name: "Astro Nikhil",
  //   image: require("@/assets/images/astrologers/astrologer3.png"),
  //   rating: 4.2,
  //   speciality: "Horary",
  //   experience: 4,
  //   price: 3.19,
  //   language: ["English", "Hindi"],
  //   orders: 50,
  //   availability: "Available",
  //   category: ["Career & Job", "Education"],
  // },
  // {
  //   id: "17",
  //   name: "Astro Ramesh",
  //   image: require("@/assets/images/astrologers/astrologer1.png"),
  //   rating: 4.3,
  //   speciality: "Western",
  //   experience: 6,
  //   price: 2.79,
  //   language: ["English", "Marathi"],
  //   orders: 80,
  //   availability: "Available",
  //   category: ["Finance & Business", "Martial Status"],
  // },
  // {
  //   id: "18",
  //   name: "Astro Anjali",
  //   image: require("@/assets/images/astrologers/astrologer2.png"),
  //   rating: 4.4,
  //   speciality: "Chinese",
  //   experience: 7,
  //   price: 4.39,
  //   language: ["English", "Hindi"],
  //   orders: 95,
  //   availability: "Available",
  //   category: ["Love & Relationship", "Kids"],
  // },
  // {
  //   id: "19",
  //   name: "Astro Deepa",
  //   image: require("@/assets/images/astrologers/astrologer3.png"),
  //   rating: 4.5,
  //   speciality: "Vastu",
  //   experience: 8,
  //   price: 3.69,
  //   language: ["English", "Malayalam"],
  //   orders: 110,
  //   availability: "Available",
  //   category: ["Career & Job", "Finance & Business"],
  // },
  // {
  //   id: "20",
  //   name: "Astro Mohan",
  //   image: require("@/assets/images/astrologers/astrologer1.png"),
  //   rating: 4.6,
  //   speciality: "Numerology",
  //   experience: 9,
  //   price: 5.79,
  //   language: ["English", "Hindi"],
  //   orders: 120,
  //   availability: "Available",
  //   category: ["Love & Relationship", "Martial Status"],
  // },
  //   {
  //     id: "21",
  //     name: "Astro Shreya",
  //     image: require("@/assets/images/astrologers/astrologer2.png"),
  //     rating: 4.7,
  //     speciality: "Tarot",
  //     experience: 10,
  //     price: 2.99,
  //     language: ["English", "Hindi"],
  //     orders: 130,
  //     availability: "Available",
  //     category: ["Kids", "Finance & Business"],
  //   },
  //   {
  //     id: "22",
  //     name: "Astro Gaurav",
  //     image: require("@/assets/images/astrologers/astrologer1.png"),
  //     rating: 4.8,
  //     speciality: "Palmistry",
  //     experience: 11,
  //     price: 3.99,
  //     language: ["English", "Hindi"],
  //     orders: 140,
  //     availability: "Available",
  //     category: ["Career & Job", "Education"],
  //   },
  //   {
  //     id: "23",
  //     name: "Astro Rachna",
  //     image: require("@/assets/images/astrologers/astrologer3.png"),
  //     rating: 4.9,
  //     speciality: "Vedic",
  //     experience: 12,
  //     price: 6.49,
  //     language: ["English", "Hindi"],
  //     orders: 150,
  //     availability: "Available",
  //     category: ["Finance & Business", "Martial Status"],
  //   },
  //   {
  //     id: "24",
  //     name: "Astro Suman",
  //     image: require("@/assets/images/astrologers/astrologer1.png"),
  //     rating: 4.1,
  //     speciality: "Prashana",
  //     experience: 13,
  //     price: 2.99,
  //     language: ["English", "Hindi"],
  //     orders: 160,
  //     availability: "Available",
  //     category: ["Love & Relationship", "Kids"],
  //   },
  //   {
  //     id: "25",
  //     name: "Astro Ritesh",
  //     image: require("@/assets/images/astrologers/astrologer2.png"),
  //     rating: 4.2,
  //     speciality: "Tarot",
  //     experience: 14,
  //     price: 3.29,
  //     language: ["English", "Hindi"],
  //     orders: 170,
  //     availability: "Available",
  //     category: ["Career & Job", "Finance & Business"],
  //   },
  //   {
  //     id: "26",
  //     name: "Astro Nisha",
  //     image: require("@/assets/images/astrologers/astrologer3.png"),
  //     rating: 4.3,
  //     speciality: "Horary",
  //     experience: 15,
  //     price: 4.59,
  //     language: ["English", "Hindi"],
  //     orders: 180,
  //     availability: "Available",
  //     category: ["Love & Relationship", "Martial Status"],
  //   },
  //   {
  //     id: "27",
  //     name: "Astro Kunal",
  //     image: require("@/assets/images/astrologers/astrologer1.png"),
  //     rating: 4.4,
  //     speciality: "Western",
  //     experience: 16,
  //     price: 5.19,
  //     language: ["English", "Hindi"],
  //     orders: 190,
  //     availability: "Available",
  //     category: ["Kids", "Finance & Business"],
  //   },
  //   {
  //     id: "28",
  //     name: "Astro Radhika",
  //     image: require("@/assets/images/astrologers/astrologer2.png"),
  //     rating: 4.5,
  //     speciality: "Chinese",
  //     experience: 17,
  //     price: 6.09,
  //     language: ["English", "Hindi"],
  //     orders: 200,
  //     availability: "Available",
  //     category: ["Career & Job", "Education"],
  //   },
  //   {
  //     id: "29",
  //     name: "Astro Sagar",
  //     image: require("@/assets/images/astrologers/astrologer1.png"),
  //     rating: 4.6,
  //     speciality: "Vastu",
  //     experience: 18,
  //     price: 3.89,
  //     language: ["English", "Hindi"],
  //     orders: 210,
  //     availability: "Available",
  //     category: ["Finance & Business", "Martial Status"],
  //   },
  //   {
  //     id: "30",
  //     name: "Astro Tanvi",
  //     image: require("@/assets/images/astrologers/astrologer2.png"),
  //     rating: 4.7,
  //     speciality: "Numerology",
  //     experience: 19,
  //     price: 5.99,
  //     language: ["English", "Hindi"],
  //     orders: 220,
  //     availability: "Available",
  //     category: ["Love & Relationship", "Kids"],
  //   },
];
