import { HistorySession } from "@/constants/types";
import { Astrologers } from "./astrologers";

export const HistoryData: HistorySession[] = [
  {
    id: "1",
    astrologer: {
      id: Astrologers[0].id,
      name: Astrologers[0].name,
      image: Astrologers[0].image,
      rating: Astrologers[0].rating,
      speciality: Astrologers[0].speciality,
    },
    sessionType: "Chat",
    duration: "15 min",
    date: "Today",
    timestamp: "2:30 PM",
    status: "Completed",
    amount: 150,
  },
  {
    id: "2",
    astrologer: {
      id: Astrologers[1].id,
      name: Astrologers[1].name,
      image: Astrologers[1].image,
      rating: Astrologers[1].rating,
      speciality: Astrologers[1].speciality,
    },
    sessionType: "Call",
    duration: "25 min",
    date: "Yesterday",
    timestamp: "6:45 PM",
    status: "Completed",
    amount: 300,
  },
  {
    id: "3",
    astrologer: {
      id: Astrologers[2].id,
      name: Astrologers[2].name,
      image: Astrologers[2].image,
      rating: Astrologers[2].rating,
      speciality: Astrologers[2].speciality,
    },
    sessionType: "Chat",
    duration: "0 min",
    date: "2 days ago",
    timestamp: "4:15 PM",
    status: "Missed",
    amount: 0,
  },
  {
    id: "4",
    astrologer: {
      id: Astrologers[3].id,
      name: Astrologers[3].name,
      image: Astrologers[3].image,
      rating: Astrologers[3].rating,
      speciality: Astrologers[3].speciality,
    },
    sessionType: "Call",
    duration: "30 min",
    date: "3 days ago",
    timestamp: "8:20 AM",
    status: "Completed",
    amount: 450,
  },
  {
    id: "5",
    astrologer: {
      id: Astrologers[4].id,
      name: Astrologers[4].name,
      image: Astrologers[4].image,
      rating: Astrologers[4].rating,
      speciality: Astrologers[4].speciality,
    },
    sessionType: "Chat",
    duration: "12 min",
    date: "1 week ago",
    timestamp: "11:30 AM",
    status: "Completed",
    amount: 120,
  },
  {
    id: "6",
    astrologer: {
      id: Astrologers[5].id,
      name: Astrologers[5].name,
      image: Astrologers[5].image,
      rating: Astrologers[5].rating,
      speciality: Astrologers[5].speciality,
    },
    sessionType: "Call",
    duration: "0 min",
    date: "1 week ago",
    timestamp: "3:00 PM",
    status: "Cancelled",
    amount: 0,
  },
];
